### ISSUE TITLE
using zipstream-ng with S3

### ISSUE THREAD

**Issue by Kurtaja** [pR0Ps/zipstream-ng#11]
Hi Carey, and thank you for a great library!
I've successfully implemented it in a flask server downloading files from the server. However, I also need to let the user stream download files from S3 buckets. And so far I've not been able to figure out how (if?) I can use your library for that. If already possible, would you have the possibility to point me in the good direction with a short example or anything that can help me get going? (And if not, you have the possibility to add that feature to your great library?)
Kind regards
Kurt

**Comment by pR0Ps** [comment]
If I understand your question properly, you have an application of some kind that uses S3 to store its data. A user can request this data from your application. When they do that, you want to stream the files from S3 into a zip file while it's streaming to the user. This avoids storing the entire file from S3 temporarily while the user downloads it.

If this is the case, it should be possible as long as whatever you're using to download data from S3 allows you to stream it. Here's a simple (untested) example of using the [`minio`](https://github.com/minio/minio-py) library to download data from an S3-compatible server as a stream into a `ZipStream`.

```python
from minio import Minio
from zipstream import ZipStream

# connect to S3 and request the object
client = Minio(
    "s3.amazonaws.com",
    access_key="YOUR-ACCESSKEYID",
    secret_key="YOUR-SECRETACCESSKEY"
)
obj = client.get_object("bucketname", "objectname")

# create the ZipStream and add the object's data stream to it
zs = ZipStream()
zs.add(
    obj.stream(amt=32*1024),  # stream data in 32KB chunks
    arcname="some_filename"
)

# At this point you can serve `zs` to the user like you did with your
# other Flask server. As they download it, the data will be streamed
# from S3 to fill it.
```

**Comment by Kurtaja** [comment]
Thanks Carey!
That works for the first 32KB chunk for each file. However, I was not able figure out how to get the rest of the chunks, nor did it inkrease the chunk size if I changed the chunk size e.g. like this 'obj.stream(amt=128*1024)'. I even increased to 5242880, as some forums suggested thats the minimum chunk size you can use(?), but still did not work. You have the possibility to send a short example showing how to do that (or point me in the good direction to get me going again)?

**Comment by pR0Ps** [comment]
I'm not sure why you would only be getting the first 32KB. I just tested the following:
```python
import urllib3
from zipstream import ZipStream

resp = urllib3.PoolManager().request("GET", "<some URL>", preload_content=False)

zs = ZipStream()
zs.add(
    resp.stream(amt=32*1024),
    arcname="some_filename"
)

with open("outfile.zip", "wb") as fp:
    fp.writelines(zs)
```

This produced an "outfile.zip" that contained a "some_filename" file that contained all the data downloaded from "\<some URL\>".

Since the `minio` library that I mentioned in the previous example uses `urllib3` under the hood (and returns the same [`HTTPResponse`](https://urllib3.readthedocs.io/en/stable/reference/urllib3.response.html#urllib3.response.HTTPResponse) object from `get_object` as the `.request` method I used here), there should be no difference when streaming the response into the zip.

**Comment by Kurtaja** [comment]
Thanks Carey!
when I investigate the 'objMyMinio' object, in my code here below, the 'chunked' variable is set to False, see the image in the bottom of this reply, I've tried to find a way to enable chunking in Minio, but was not able to find it. Do you have an idea what could be wrong?

`
from minio import Minio
from zipstream import ZipStream

@app.route('/')
@app.route('/home')
def home():

    try:
        sBucketName = "myBucket"
        sFolderName = "myFolder"
        myMinioClient = Minio(
            "my_cloudy.com",
            access_key='MY_ACC_KEY',
            secret_key='MY_SCR_KEY',
            region="s3.us-west-1"
        )
		diFiles = myFunctionForListingTheFilesToDownload()
		zs = ZipStream()
        for sFile in diFiles:
			sPathAndFile = os.path.join(sFolderName, sFile['name']).replace('\\', '/')
            objMyMinio = myMinioClient.get_object(myBucketName, sFile['name'])
            zs.add(
                objMyMinio.stream(amt=32*1024),  # stream data in 32KB chunks
                arcname=sFile['name']
            )
        return Response(
            zs,
            mimetype="application/zip",
            headers={
                "Content-Disposition": f"attachment; filename={name}.zip",
                #"Content-Length": iLen,
                "Last-Modified": zs.last_modified,
            }
        )
    except OSError as err:
        sErr = "Error in function 'home'. OS error: {0}".format(err)
    except BaseException as err:
        bErr = True
        sErr = "Error in function 'home'. " + str(err)
`
![image](https://user-images.githubusercontent.com/62388983/207927502-16cef401-c458-4a3a-8198-50ff1d10aa03.png)

**Comment by Kurtaja** [comment]
Thanks Carey!
when I investigate the 'objMyMinio' object, in my code here below, the 'chunked' variable is set to False, see the image in the bottom of this reply, I've tried to find a way to enable chunking in Minio, but was not able to find it. Do you have an idea what could be wrong?

`
from minio import Minio
from zipstream import ZipStream

@app.route('/')
@app.route('/home')
def home():

    try:
        sBucketName = "myBucket"
        sFolderName = "myFolder"
        myMinioClient = Minio(        
		    "my_cloudy.com",
		    access_key='MY_ACC_KEY',
		    secret_key='MY_SCR_KEY',
		    region="s3.us-west-1"
        )
        diFiles = myFunctionForListingTheFilesToDownload()
        zs = ZipStream()
        for sFile in diFiles:
		    sPathAndFile = os.path.join(sFolderName, sFile['name']).replace('\\', '/')
		    objMyMinio = myMinioClient.get_object(myBucketName, sFile['name'])
		    zs.add(
		        objMyMinio.stream(amt=32*1024),  # stream data in 32KB chunks
		        arcname=sFile['name']
		    )
        return Response(
		    zs,
		    mimetype="application/zip",
		    headers={
		        "Content-Disposition": f"attachment; filename={name}.zip",
		        "Last-Modified": zs.last_modified,
		    }
        )
    except OSError as err:
        sErr = "Error in function 'home'. OS error: {0}".format(err)
    except BaseException as err:
        sErr = "Error in function 'home'. " + str(err)
`

![image](https://user-images.githubusercontent.com/62388983/207932680-147c0b04-d24f-4e86-97e1-e2f642f9089a.png)


PS sorry for posting the reply twize (there were some indent errors due to tab's in my code file)

**Comment by pR0Ps** [comment]
A response doesn't need to be chunked in order to be streamable - `urllib3` can just only read data from the socket as it's requested instead of reading it all into memory at once. What you have looks like it should be doing this - I tested something extremely similar to your code with `minio` and it streamed chunks of the file just fine. I verified that the program would alternate between grabbing a chunk from the `obj.stream()` iterator and writing that chunk into the ZipStream as it was iterated over.

If what you have isn't working, I would suggest first making sure that iterating over the `objMyMinio.stream()` yields the byte chunks that you expect without putting it into the `ZipStream`. If it just yields the entire response all at once then there's nothing this library can do. However, if it properly yields chunks of data but the `ZipStream` is pulling all of them into memory (without being constructed with `sized=True`, see the `ZipStream.__init__` docstring) then that's definitely a bug.

As a sidenote, while looking at the `minio` and `urllib3` docs, I noticed that they recommend cleaning up the response after downloading all the data from it. Since I provided some `minio` example code above, I've edited it to take this into account.

Some resources I looked at while writing this that you may find helpful:
 - https://urllib3.readthedocs.io/en/stable/reference/urllib3.response.html#urllib3.response.HTTPResponse.stream
 - https://urllib3.readthedocs.io/en/stable/advanced-usage.html#streaming-and-i-o
 - https://min.io/docs/minio/linux/developers/python/API.html#get_object

**Comment by Kurtaja** [comment]
Thanks for your help Carey!
I now successfully manage to stream the files from S3 to the user using minio and zipstream-ng in Flask! 

1)
However, I think the minio get_object function is quite slow. When the user wants to download a folder or recursive folder structure, Is there a way to fetch a path/folder object in minio and feed it to zipstream instead of having to call the minio get_object function for each file? I could not find anything  in the API about it, and if I just try to give a path (without file name) to the get_object function it throws an error.

2)
I know this question does not belong here, but maybe if you have done the same thing you have the possibility to point me in the good direction? I'm using dropzone for file upload to the server, with chunking and parallel chunk upload and it's amazingly fast! So I'd like to do the same for upload from my Flask application to S3. But I'm struggling a bit to get my head around how to set it up and use it with pre signed url  etc. Do you happen to have some example code or anything that could point me in the good direction for that?

**Comment by pR0Ps** [comment]
Glad you got it working! Make sure that you use at least `zipstream-ng` v1.3.5 as it fixed an issue where adding iterables (what you're doing) would generate file headers in the zip that some programs warned about when extracting. See #13 for more details.

As for your questions, I'm not that familiar with `minio` specifically or even interacting with S3-style storage at all so I'd recommend reading the `minio` docs and asking in their support channels for that instead, sorry.
